language: objective-c
osx_image: xcode8
script:
  - set -o pipefail
  - pwd
  - which xcodebuild
  - type xcodebuild
  - xcodebuild -version
  - xcodebuild -showsdks
  - cp -rv ./Tests /private/tmp/ # Hack for Travis
  - make build-for-coverage
after_success:
  - bash <(curl -s https://codecov.io/bash)
